services:
  convite-casamento:
    build:
      context: .
      args:
        API_URL: ${API_URL}
    container_name: convite-casamento
    restart: always
    networks:
      - proxy
    ports:
      - "3097:3097" 
    environment:
      API_URL: ${API_URL}

networks:
  proxy:
    external: true
